### ISSUE TITLE
Azure: Not possible to create Lifecycle Rule to Archive Blob after 1 day

### ISSUE THREAD

**Issue by gunar** [nelsonjchen/gargantuan-takeout-rocket#2]
Thanks for GTR. Super excited about finally trying it out.

Instructions tell me to create two lifecycle rules. One to delete a blob after 180d, and one to archive a blob after 1 day. I can't figure out how to create a Rule for the latter:

https://github.com/nelsonjchen/gargantuan-takeout-rocket/blob/acc73384c2665d6b25e7353a7592b0207adfb1cb/README.md?plain=1#L58

![image](https://user-images.githubusercontent.com/7684574/183769302-365fa9cb-300a-4dc6-b896-eef0ab0fec29.png)

**Comment by nelsonjchen** [comment]
I have this setup:

<img width="938" alt="Screen Shot 2022-08-09 at 4 11 49 PM" src="https://user-images.githubusercontent.com/5363/183777568-6411c699-87e5-490e-a29e-cedb06ed4e4c.png">

Is this in a region that doesn't have this product or something?

https://azure.microsoft.com/en-us/global-infrastructure/services/?products=storage&regions=all

**Comment by gunar** [comment]
"Append blobs" must be un-selected for the option to become available. Thanks!

![image](https://user-images.githubusercontent.com/7684574/184217565-8933c78a-d559-4ac1-9683-7149e588c345.png)


Before we close this issue, quick question: Why don't we immediately upload blobs in the Archive tier? Wouldn't that remove the need for this extra lifecycle rule while also making hosting cheaper since we don't have to wait for 1 day to move it to ~cold~ archive storage?

Thanks again for GTR.

**Comment by nelsonjchen** [comment]
I guess I just liked being able to delete stuff without paying for their storage if I didn't want to actually archive it and sometimes I made that decision after checking the file listing of the container at the conclusion of the archiving session or activity.

**Comment by gunar** [comment]
Makes total sense. Thank you for your prompt responses. GTR is f-ing awesome.
